language: java
jdk:
- oraclejdk8
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: saurav.a.singh@capgemini.com
  password:
    secure: fUHqZLmfxG5tQ+JB0enRVH8oS/M0r1NzJ3JuGWKWV3RJJQckx0jQqvcokbDLtqPejyxR2xlSWr7Nbgtbc2ohigg/DYhvETAN+zpC0i4ksXkWOhoE2tuzbJBZZ96t/hdo7D87HE2wnrANuJ+YioPVi8pVm3mWf4Yyikbda+MtUlDwRfq+ygBMX8m1IwgztsFfR+eYva54tMevVIS2lVi+19cDe+6BxCQJwsnmov9brrfFvza6oxroVhucK2Pynt/bXg5iBNx9JI4oO8zzhcDIHjALPbEd3Fa7o3xArOuKKOjuiktByxgaPFYrRwpNpe4teLhCVXrVFx0pSkzMzIDl53Xlgb4oY1lN4FXxGoauSZrTFaEA2kuUVX5EPcP1zhWfnkKYoAX/wiyMp4MJdKZDnKGbL8MvkJt80JirWZu27xrgK8M70vcpd/aKwyoLPqLIFVgZpMluec1HInD65xVh9zvXpd6T8qaBwf3VY4NK3zwz+EPze4dOQLzvk0vx4dji6njGyQ+NYvGY5pafDIQeGvaO1is9Ut29e+ySQymeLfQar9Wej87+pkk9UNvNDkxetNHV2H1AZU/vxbSiwM5HpXgMqQTaIbJjXWJJCMavzZe8ZRxObslyY64KtMyQWzxVyNdr+VKa4wss7ciwnGV2IYVZxPqFDhLQhzLVTPbZA3Y=
  organization: reddevils
  space: development
  manifest: manifest.yml
  on:
    repo: sauravsingh29/tech-soultion
